import {SpaceGaugesComposition, SpaceGaugesCompSchema} from './compositions/SpaceGaugesComposition';
import {SpinningStarsComposition, SpinningStarsCompSchema} from './compositions/SpinningStarsComposition';
import {DeathStarComposition, deathStarSchema} from './compositions/DeathStarComposition';
import {TargetingComputerComposition, targetingComputerCompSchema} from './compositions/TargetingComputerComposition';
import {DonutShieldComposition, donutShieldCompSchema} from './compositions/DonutShieldComposition';
import {EpicRadarComposition, epicRadarCompSchema} from './compositions/EpicRadarComposition';
import {AlertSphereComposition, alertSphereCompSchema} from './compositions/AlertSphereComposition';
import {SimpleStarsComposition, SimpleStarsSchema} from './compositions/SimpleStarsComposition';
import {ScifiGridComposition, scifiGridSchema} from './compositions/ScifiGridComposition';
import {HothLaserComposition, HothLaserCompSchema} from './compositions/HothLaserComposition';
import {RetroSunComposition, RetroSunCompSchema} from './compositions/RetroSunComposition';
import {Planet3DComposition, Planet3DCompSchema} from './compositions/Planet3DComposition';
import {GalacticMapComposition, GalacticMapCompSchema} from './compositions/GalacticMapComposition';
import {SpaceSpiralComposition, SpaceSpiralSchema} from './compositions/SpaceSpiralComposition';

export const compositions = {
      SimpleStars: {
        component: SimpleStarsComposition,
        durationInFrames: 300,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: SimpleStarsSchema,
        defaultProps: {
          starCount: 2000,
          speed: 2,
          starColor: '#FFFFFF',
        },
      },
      DeathStar: {
        component: DeathStarComposition,
        durationInFrames: 120 * 30, // 30 * 1 * 60 * 6, 10471
        fps: 30,
        width: 1920,
        height: 1080,
        schema: deathStarSchema,
        defaultProps: {
          color: '#CCCCCC',
          darknessFactor: 70,
          rotationSpeed: 3,
        },
      },
      TargetingComputer: {
        component: TargetingComputerComposition,
        durationInFrames: 30 * 60 * 5,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: targetingComputerCompSchema,
        defaultProps: {
          animationSpeed: 80,
          lineGap: 25,
          numberOfLines: 12,
          acceleration: 5,
          lineColor: '#ffff00',
          numberColor: '#ff0000',
          fontSize: 128,
        },
      },
      DonutShield: {
        component: DonutShieldComposition,
        durationInFrames: 3000,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: donutShieldCompSchema,
        defaultProps: {
          donutRotationSpeed: 10,
          message1: 'Quantum flux stabilizers online',
          message2: 'Tachyon particle harmonics nominal',
          message3: 'Subspace field integrity at 98.7%',
          message4: 'Neutrino dampeners functioning optimally',
          donutColor: '#0f0',
          innerCircleColor: 'hsl(180, 100%, 50%)',
          middleCircleColor: 'hsl(200, 100%, 50%)',
          outerCircleColor: 'hsl(220, 100%, 50%)',
          textColor: '#0f0',
        },
      },
      EpicRadar: {
        component: EpicRadarComposition,
        durationInFrames: 1800,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: epicRadarCompSchema,
        defaultProps: {
          backgroundColor: 'black',
          radarColor: 'rgb(255, 0, 0)',
          terrainDotColor: 'rgb(255, 0, 0)',
          radarSpeed: 15,
          terrainPointCount: 50,
          terrainMinDistance: 10,
          terrainMaxDistance: 95,
          terrainSeed: 12345,
          terrainPointSize: 2,
        },
      },
      AlertSphere: {
        component: AlertSphereComposition,
        durationInFrames: 900,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: alertSphereCompSchema,
        defaultProps: {
          sphereColor: '#00FF00',
          backgroundColor: '#000000',
          redLabelColor: '#FF0000',
          greenLabelColor: '#00FF00',
          rotationSpeed: 1,
          sphereSizeRatio: 4,
          tiltAngle: 32.5,
          greenMessage1: 'Spacecraft leaving atmosphere',
          greenMessage2: 'Small explosion detected',
          greenMessage3: 'Bespin gas leak detected',
          greenMessage4: 'Abnormal radio interference',
          greenMessage5: 'Outpost communication lost',
          redMessage1: 'Outpost alarm activated',
          redMessage2: 'Known outlaw sighted',
          redMessage3: 'Unauthorized spacecraft detected',
          redMessage4: 'Emergency signal received',
          redMessage5: 'Significant combat activity detected',
          useAurekBesh: true,
        },
      },
      SpinningStars: {
        component: SpinningStarsComposition,
        durationInFrames: 30 * 30 * 5,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: SpinningStarsCompSchema,
        defaultProps: {
          starCount: 10083,
          slowStarSpeed: 0.05,
          fastStarSpeed: 20,
          slowTailLength: 0.01,
          fastTailLength: 25,
          phaseDuration: 5,
          transitionDuration: 10,
          defaultStarColor: '#c7d5ff',
          fastStarColor: '#1899fb',
          regenerateStarsEachFrame: false,
          rotationSpeed: 3,
        },
      },
      SpaceGauges: {
        component: SpaceGaugesComposition,
        durationInFrames: 300,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: SpaceGaugesCompSchema,
        defaultProps: {
          firstGaugeName: 'Energy',
          secondGaugeName: 'Shields',
          thirdGaugeName: 'Thrust',
          toggleStars: true,
          starsSpeed: 2,
          textColor: '#00FFFF',
          gaugeColor: '#00FFFF',
          criticalColor: '#FF0000',
          cautionColor: '#FFFF00',
          optimalColor: '#00FF00',
        },
      },
      HothLaser: {
        component: HothLaserComposition,
        durationInFrames: 300,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: HothLaserCompSchema,
        defaultProps: {
          triangleCount: 5,
          triangleSize: 32,
        },
      },
      RetroSun: {
        component: RetroSunComposition,
        durationInFrames: 3000,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: RetroSunCompSchema,
        defaultProps: {
          speed: 46,
          backgroundColor: '#13041f',
          gridColor: 'rgba(128, 0, 128, 0.5)',
          starColor: '#FFFFFF',
          sunGradientColor1: '#FFD700',
          sunGradientColor2: '#FF1493',
          sunGradientColor3: '#8A2BE2',
          numberOfStars: 71,
          minStarSize: 1,
          maxStarSize: 6,
          sunDiameter: 925,
          starMovementSpeed: 58,
          numberOfMountainPoints: 23,
        },
      },
      SpaceSpiral: {
        component: SpaceSpiralComposition,
        durationInFrames: 1800,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: SpaceSpiralSchema,
        defaultProps: {
          turns: 42,
          height: 20,
          radius: 3,
          segments: 800,
          spiralColor: '#FFFF00',
          starCount: 100,
          minStarSize: 0.5,
          maxStarSize: 1.0,
          zoomLevel: 7,
          spiralRotation: 270,
          screenRotation: 60,
          screenRotationSpeed: 12,
          toggleRainbowEffect: false,
          seed: 12345,
        },
      },
      PolygonSpiral: {
        component: SpaceSpiralComposition,
        durationInFrames: 1800,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: SpaceSpiralSchema,
        defaultProps: {
          turns: 159,
          height: 20,
          radius: 2,
          segments: 800,
          spiralColor: "#a8ffc2",
          starCount: 182,
          minStarSize: 1,
          maxStarSize: 2,
          zoomLevel: 9,
          spiralRotation: 273,
          screenRotation: 60,
          screenRotationSpeed: -2,
          toggleRainbowEffect: false,
          seed: 12345,
        },
      },
      HalcyonMap: {
        component: GalacticMapComposition,
        durationInFrames: 1 * 60 * 24,
        fps: 1,
        width: 1920,
        height: 1080,
        schema: GalacticMapCompSchema,
        defaultProps: {
          messageText: 'Welcome Home',
          locationText: 'Home',
          cabinText: '',
          topLettersColor: '#c3e0ff',
          primaryColor: '#2699F4',
          secondaryColor: '#0289fd',
          keyPriColor: '#dcff85',
          keySecColor: '#dcff85',
          planetsColor: '#378afb',
          jumpsColor: '#dcff85',
          pathColor: '#dcff85',
          routesColor: 'rgba(3, 58, 186, 0.80)',
          regionColor: '#051738',
          altPlanetColor: '#0060e3',
          graphColor: '#133897',
          smPathColor: '#051738',
          backgroundColor: '#000000',
          regionTextColor: '#3381eb',
          showCircle: true,
          logo: 'halcyon' as const,
          changeIntervalInSeconds: 60,
        },
      },
      RebelMap: {
        component: GalacticMapComposition,
        durationInFrames: 1 * 60 * 24,
        fps: 1,
        width: 1920,
        height: 1080,
        schema: GalacticMapCompSchema,
        defaultProps: {
          messageText: 'Ignite the Spark',
          locationText: 'Cabin',
          cabinText: '3222',
          topLettersColor: '#030409',
          primaryColor: '#af3a12',
          secondaryColor: '#dd4e1e',
          keyPriColor: '#AFAFAF',
          keySecColor: '#FFFFFF',
          planetsColor: '#939393',
          jumpsColor: '#DCFF85',
          pathColor: '#86985B',
          routesColor: '#171819',
          regionColor: '#994500',
          altPlanetColor: '#2B0000',
          graphColor: '#2D0909',
          smPathColor: '#313234',
          backgroundColor: '#000000',
          regionTextColor: '#ffffff',
          showCircle: false,
          logo: 'rebel' as const,
          changeIntervalInSeconds: 60,
        },
      },
      BobaFettMap: {
        component: GalacticMapComposition,
        durationInFrames: 1 * 60 * 24,
        fps: 1,
        width: 1920,
        height: 1080,
        schema: GalacticMapCompSchema,
        defaultProps: {
          messageText: 'Boba Fett',
          locationText: 'Mandalore',
          cabinText: '1980',
          topLettersColor: '#030409',
          primaryColor: '#5a4d26',
          secondaryColor: '#217e20',
          keyPriColor: '#AFAFAF',
          keySecColor: '#FFFFFF',
          planetsColor: '#939393',
          jumpsColor: '#DCFF85',
          pathColor: '#86985B',
          routesColor: '#171819',
          regionColor: '#7e3535',
          altPlanetColor: '#2B0000',
          graphColor: '#2D0909',
          smPathColor: '#313234',
          backgroundColor: '#000000',
          regionTextColor: '#b57d7d',
          showCircle: true,
          logo: 'mandalorian' as const,
          changeIntervalInSeconds: 60,
        },
      },
      FirstOrderMap: {
        component: GalacticMapComposition,
        durationInFrames: 1 * 60 * 24,
        fps: 1,
        width: 1920,
        height: 1080,
        schema: GalacticMapCompSchema,
        defaultProps: {
          messageText: 'FOR THE ORDER',
          locationText: 'Cabin',
          cabinText: '7320',
          topLettersColor: '#030409',
          primaryColor: '#B20007',
          secondaryColor: '#B20007',
          keyPriColor: '#AFAFAF',
          keySecColor: '#FFFFFF',
          planetsColor: '#939393',
          jumpsColor: '#DCFF85',
          pathColor: '#86985B',
          routesColor: '#171819',
          regionColor: '#9A0000',
          altPlanetColor: '#2B0000',
          graphColor: '#2D0909',
          smPathColor: '#313234',
          backgroundColor: '#000000',
          regionTextColor: '#b57d7d',
          showCircle: true,
          logo: 'firstorder' as const,
          changeIntervalInSeconds: 60,
        },
      },
      ImperialMap: {
        component: GalacticMapComposition,
        durationInFrames: 1 * 60 * 24,
        fps: 1,
        width: 1920,
        height: 1080,
        schema: GalacticMapCompSchema,
        defaultProps: {
          messageText: 'Long live the Empire',
          locationText: 'EMPIRE',
          cabinText: '1980',
          topLettersColor: '#030409',
          primaryColor: '#750004',
          secondaryColor: '#B20007',
          keyPriColor: '#AFAFAF',
          keySecColor: '#FFFFFF',
          planetsColor: '#939393',
          jumpsColor: '#DCFF85',
          pathColor: '#86985B',
          routesColor: '#171819',
          regionColor: '#9A0000',
          altPlanetColor: '#2B0000',
          graphColor: '#2D0909',
          smPathColor: '#313234',
          backgroundColor: '#000000',
          regionTextColor: '#b57d7d',
          showCircle: false,
          logo: 'imperial' as const,
          changeIntervalInSeconds: 60,
        },
      },
      ScifiGrid: {
        component: ScifiGridComposition,
        durationInFrames: 1500,
        fps: 30,
        width: 1920,
        height: 1080,
        schema: scifiGridSchema,
        defaultProps: {
          backgroundColor: '#000000',
          gridColor: '#0066cc',
          scanLineColor: '#00ccff',
          animationSpeed: 1,
          gridSpacing: 50,
        },
      }
} as const;

export type CompIds = keyof typeof compositions;